### ISSUE TITLE
[Errno 2] No such file or directory: 'kitti-data/raw/mapping/train_mapping.txt'

### ISSUE THREAD

**Issue by hadi-ghnd** [NVIDIA/DIGITS#1499]
I'm trying to perform object detection using digits on KITTI, following [these](https://github.com/NVIDIA/DIGITS/tree/master/examples/object-detection) instructions. I downloaded the 3 files to the specified directory. Now when I try to use `./prepare_kitti_data.py`, I get this error:

> Extracting zipfiles ...
> Unzipping data_object_label_2.zip ...
> Unzipping data_object_image_2.zip ...
> Unzipping devkit_object.zip ...
> Calculating image to video mapping ...
> Traceback (most recent call last):
>   File "./prepare_kitti_data.py", line 182, in <module>
>     os.path.join(args.output_dir, 'raw'),
>   File "./prepare_kitti_data.py", line 39, in get_image_to_video_mapping
>     with open(os.path.join(devkit_dir, 'mapping', 'train_mapping.txt'), 'r') as infile:
> IOError: [Errno 2] No such file or directory: 'kitti-data/raw/mapping/train_mapping.txt'

What can I do to make this work?

**Comment by hadi-ghnd** [comment]
The problem is solved. The **kitti-data/raw** folder should include these:
cpp
mapping
matlab
testing
training
readme.txt

**Comment by ianthomas** [comment]
Following these instructions and getting this exact error.  I've just pulled master, and downloaded the files from kitti today. 

my kitti-data/raw/ folder only has:
devkit
testing
training

I don't see a PR for this issue, was the fix in prepare_kitti_data.py?

**Comment by mhtrinh** [comment]
I checkout the latest master as today and downloaded the kitti data yesterday : the issue is still there ! Please re-open the issue.

**Comment by gaoliangmi** [comment]
I checkout the latest master as today and downloaded the kitti data today : the issue is still there ! Please re-open the issue.

**Comment by yasenh** [comment]
https://github.com/NVIDIA/DIGITS/blob/master/examples/object-detection/prepare_kitti_data.py#L181-L183

Add 'devkit' after 'raw':
```
mapping = get_image_to_video_mapping(
        os.path.join(args.output_dir, 'raw', 'devkit'),
    )
```

**Comment by mflaxman10** [comment]
Confirmed yasenh's patch worked for me - can you make a pull request for it?
